import React, { useState } from 'react';
import {
  FileText,
  Copy,
  Check,
  Clock,
  User,
  ShieldAlert,
  CheckCircle2,
  Eye,
  Ticket,
  AlertTriangle,
  MessageSquare,
  GitCommit,
  Layers,
  Sparkles,
} from 'lucide-react';
import { HandoverReport, ProcessedActivity, HandoverCategory, SourceType } from '../types';
import { formatDateTimeDisplay, calculateDurationHours } from '../utils/dateUtils';

interface HandoverPreviewProps {
  report: HandoverReport;
  onClose: () => void;
}

const CATEGORY_META: Record<
  HandoverCategory,
  {
    title: string;
    emoji: string;
    icon: React.ElementType;
    badgeClass: string;
    borderClass: string;
    bgClass: string;
  }
> = {
  BLOCKERS: {
    title: 'BLOCKERS / ESCALATIONS',
    emoji: '🚨',
    icon: ShieldAlert,
    badgeClass: 'bg-rose-100 text-rose-800 border-rose-200',
    borderClass: 'border-rose-200',
    bgClass: 'bg-rose-50/30',
  },
  IN_PROGRESS: {
    title: 'IN PROGRESS',
    emoji: '🔄',
    icon: Clock,
    badgeClass: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    borderClass: 'border-indigo-200',
    bgClass: 'bg-indigo-50/30',
  },
  WATCH_LIST: {
    title: 'WATCH-LIST',
    emoji: '👀',
    icon: Eye,
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-200',
    borderClass: 'border-amber-200',
    bgClass: 'bg-amber-50/30',
  },
  COMPLETED: {
    title: 'COMPLETED',
    emoji: '✅',
    icon: CheckCircle2,
    badgeClass: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    borderClass: 'border-emerald-200',
    bgClass: 'bg-emerald-50/30',
  },
};

export const HandoverPreview: React.FC<HandoverPreviewProps> = ({ report, onClose }) => {
  const [copied, setCopied] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<'preview' | 'raw'>('preview');

  const duration = calculateDurationHours(
    report.config.startDateTime,
    report.config.endDateTime
  );

  const getSourceBadge = (source: SourceType) => {
    switch (source) {
      case 'ticketing':
        return 'bg-blue-50 text-blue-700 border-blue-200';
      case 'incident':
        return 'bg-rose-50 text-rose-700 border-rose-200';
      case 'chat':
        return 'bg-purple-50 text-purple-700 border-purple-200';
      case 'commit':
        return 'bg-emerald-50 text-emerald-700 border-emerald-200';
    }
  };

  const getSourceIcon = (source: SourceType) => {
    switch (source) {
      case 'ticketing':
        return <Ticket className="w-3.5 h-3.5 text-blue-600" />;
      case 'incident':
        return <AlertTriangle className="w-3.5 h-3.5 text-rose-600" />;
      case 'chat':
        return <MessageSquare className="w-3.5 h-3.5 text-purple-600" />;
      case 'commit':
        return <GitCommit className="w-3.5 h-3.5 text-emerald-600" />;
    }
  };

  // Generate plain text / markdown strictly structured into the 4 sections
  const generateMarkdown = () => {
    const formatSectionMd = (catKey: HandoverCategory, label: string) => {
      const items = report.categorized[catKey] || [];
      let md = `### ${label} (${items.length})\n`;
      if (items.length === 0) {
        md += `Nothing to report.\n\n`;
      } else {
        items.forEach((item) => {
          md += `- **[${item.source.toUpperCase()}] ${item.recordId}** | Timestamp: ${item.displayTimestamp} (ISO: ${item.normalizedTimestamp})\n`;
          md += `  * Summary: ${item.summary}\n`;
          md += `  * Status: ${item.status} | Priority: ${item.priority}\n`;
          if (item.handoffNotes) {
            md += `  * Handoff Note: ${item.handoffNotes}\n`;
          }
        });
        md += `\n`;
      }
      return md;
    };

    return `# SHIFT HANDOVER NOTE
**Shift Lead**: ${report.config.employeeName}${report.config.employeeRole ? ` (${report.config.employeeRole})` : ''}
**Shift Window**: ${formatDateTimeDisplay(report.config.startDateTime)} to ${formatDateTimeDisplay(report.config.endDateTime)} (${duration})
**Report ID**: ${report.id}
**Generated**: ${formatDateTimeDisplay(report.generatedAt)}

---

## 1. EXECUTIVE BRIEFING
${report.summary}

---

## 2. SYNTHESIZED SHIFT ACTIVITIES BY CATEGORY

${formatSectionMd('BLOCKERS', '🚨 BLOCKERS / ESCALATIONS')}
${formatSectionMd('IN_PROGRESS', '🔄 IN PROGRESS')}
${formatSectionMd('WATCH_LIST', '👀 WATCH-LIST')}
${formatSectionMd('COMPLETED', '✅ COMPLETED')}

---
*Generated by Shift Handover Note Generator • Strictly Grounded in Real/Mock Events*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const orderOfCategories: HandoverCategory[] = [
    'BLOCKERS',
    'IN_PROGRESS',
    'WATCH_LIST',
    'COMPLETED',
  ];

  return (
    <div
      id="handover-preview-modal"
      className="bg-white rounded-2xl border border-indigo-100 shadow-xl overflow-hidden mt-6 transition-all"
    >
      {/* Top Banner Header */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white p-5 sm:p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-500/20 border border-indigo-400/30 flex items-center justify-center text-indigo-300">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <span className="text-xs uppercase tracking-widest text-indigo-400 font-semibold font-mono">
                  Synthesized Document
                </span>
                <span className="px-2 py-0.5 rounded text-2xs font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  Ready
                </span>
              </div>
              <h2 className="text-xl font-bold tracking-tight text-white mt-0.5">
                Shift Handover Note
              </h2>
            </div>
          </div>

          <div className="flex items-center space-x-2 self-end sm:self-auto">
            {/* View Mode Toggle */}
            <div className="bg-slate-800/80 p-1 rounded-lg border border-slate-700 text-xs flex">
              <button
                id="view-rendered-tab"
                onClick={() => setActiveTab('preview')}
                className={`px-3 py-1 rounded-md font-medium transition-colors ${
                  activeTab === 'preview'
                    ? 'bg-indigo-600 text-white'
                    : 'text-slate-300 hover:text-white'
                }`}
              >
                Formatted Note
              </button>
              <button
                id="view-markdown-tab"
                onClick={() => setActiveTab('raw')}
                className={`px-3 py-1 rounded-md font-medium transition-colors ${
                  activeTab === 'raw'
                    ? 'bg-indigo-600 text-white'
                    : 'text-slate-300 hover:text-white'
                }`}
              >
                Markdown
              </button>
            </div>

            {/* Copy Button */}
            <button
              id="copy-handover-button"
              type="button"
              onClick={handleCopy}
              className="inline-flex items-center px-3.5 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 border border-white/20 text-white text-xs font-semibold transition-colors"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 mr-1.5 text-emerald-400" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5 mr-1.5" />
                  Copy Markdown
                </>
              )}
            </button>
          </div>
        </div>

        {/* Metadata Strip */}
        <div className="mt-5 pt-4 border-t border-slate-800 grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
          <div>
            <span className="text-slate-400 block font-medium">Shift Lead:</span>
            <span className="font-semibold text-white flex items-center mt-0.5">
              <User className="w-3.5 h-3.5 mr-1 text-indigo-400" />
              {report.config.employeeName}
            </span>
          </div>

          <div>
            <span className="text-slate-400 block font-medium">Shift Window:</span>
            <span className="font-mono text-white flex items-center mt-0.5">
              <Clock className="w-3.5 h-3.5 mr-1 text-indigo-400" />
              {duration}
            </span>
          </div>

          <div>
            <span className="text-slate-400 block font-medium">Interval:</span>
            <span className="text-slate-200 text-2xs truncate block mt-0.5 font-mono">
              {formatDateTimeDisplay(report.config.startDateTime)} – {formatDateTimeDisplay(report.config.endDateTime)}
            </span>
          </div>

          <div>
            <span className="text-slate-400 block font-medium">Total Synthesized:</span>
            <span className="font-bold text-white mt-0.5 block">
              {report.events.length} activities grounded
            </span>
          </div>
        </div>
      </div>

      {/* Body Content */}
      <div className="p-5 sm:p-7">
        {activeTab === 'raw' ? (
          <div className="relative">
            <pre className="p-4 bg-slate-900 text-slate-100 rounded-xl text-xs font-mono overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[600px] border border-slate-800">
              {generateMarkdown()}
            </pre>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Executive Summary */}
            <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-5">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2 flex items-center gap-1.5">
                <Layers className="w-4 h-4 text-indigo-600" />
                Shift Executive Summary
              </h3>
              <p className="text-sm text-slate-800 leading-relaxed font-normal">
                {report.summary}
              </p>
            </div>

            {/* Exactly Four Categorized Sections */}
            <div className="space-y-5">
              <div className="flex items-center justify-between">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-700">
                  Categorized Operational Activities (4 Main Sections)
                </h3>
                <span className="text-2xs text-slate-400 font-mono">
                  Grounding: 100% sourced from verified events
                </span>
              </div>

              {orderOfCategories.map((catKey) => {
                const meta = CATEGORY_META[catKey];
                const items = report.categorized[catKey] || [];
                const Icon = meta.icon;

                return (
                  <div
                    key={catKey}
                    className={`border ${meta.borderClass} rounded-xl overflow-hidden bg-white`}
                  >
                    {/* Section Header */}
                    <div
                      className={`px-4 py-2.5 ${meta.bgClass} border-b ${meta.borderClass} flex items-center justify-between`}
                    >
                      <div className="flex items-center space-x-2">
                        <span className="text-base">{meta.emoji}</span>
                        <span className="text-xs font-bold text-slate-900 tracking-wide uppercase">
                          {meta.title}
                        </span>
                      </div>
                      <span className={`text-xs font-bold px-2 py-0.5 rounded ${meta.badgeClass}`}>
                        {items.length} {items.length === 1 ? 'record' : 'records'}
                      </span>
                    </div>

                    {/* Section Items or "Nothing to report." */}
                    <div className="divide-y divide-slate-100">
                      {items.length === 0 ? (
                        <div className="p-4 text-center">
                          <p className="text-xs font-medium italic text-slate-400">
                            Nothing to report.
                          </p>
                        </div>
                      ) : (
                        items.map((item, itemIdx) => (
                          <div
                            key={`${item.source}:${item.recordId}:${itemIdx}`}
                            className="p-3.5 text-xs hover:bg-slate-50/50 transition-colors"
                          >
                            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-2">
                              <div className="space-y-1">
                                <div className="flex flex-wrap items-center gap-1.5">
                                  {/* Source */}
                                  <span
                                    className={`inline-flex items-center space-x-1 px-1.5 py-0.2 rounded text-3xs font-semibold border ${getSourceBadge(
                                      item.source
                                    )}`}
                                  >
                                    {getSourceIcon(item.source)}
                                    <span className="capitalize">{item.source}</span>
                                  </span>

                                  {/* Record ID */}
                                  <span className="font-mono font-bold text-slate-900 bg-slate-100 px-1.5 py-0.2 rounded border border-slate-200 text-3xs">
                                    {item.recordId}
                                  </span>

                                  {/* Status */}
                                  <span className="text-3xs px-1.5 py-0.2 rounded bg-slate-100 text-slate-700">
                                    {item.status}
                                  </span>

                                  {/* Priority */}
                                  <span className="text-3xs text-slate-500 font-medium">
                                    • {item.priority}
                                  </span>
                                </div>

                                <p className="font-semibold text-slate-900 mt-1">
                                  {item.summary}
                                </p>

                                {item.handoffNotes && (
                                  <p className="text-rose-900 bg-rose-50/60 p-2 rounded border border-rose-200/50 text-2xs mt-1">
                                    <strong>Handoff: </strong>
                                    {item.handoffNotes}
                                  </p>
                                )}
                              </div>

                              {/* Timestamp strictly shown for every item */}
                              <div className="shrink-0 text-right font-mono text-2xs text-slate-500">
                                <div>{item.displayTimestamp}</div>
                                <div className="text-3xs text-slate-400">
                                  {item.normalizedTimestamp.split('T')[1]}
                                </div>
                              </div>
                            </div>
                          </div>
                        ))
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Footer controls */}
        <div className="mt-6 pt-4 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-3">
          <span className="text-xs text-slate-500">
            Shift Handover ID: <code className="font-mono text-slate-700">{report.id}</code>
          </span>

          <div className="flex items-center space-x-2">
            <button
              id="close-preview-button"
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-lg text-xs font-semibold text-slate-600 hover:text-slate-900 hover:bg-slate-100 transition-colors"
            >
              Back to Activity Review
            </button>
            <button
              id="copy-handover-footer-btn"
              type="button"
              onClick={handleCopy}
              className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold shadow-2xs transition-colors inline-flex items-center"
            >
              {copied ? <Check className="w-3.5 h-3.5 mr-1.5 text-emerald-300" /> : <Copy className="w-3.5 h-3.5 mr-1.5" />}
              {copied ? 'Copied Handover Note' : 'Copy Handover Note'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
